[package]
name = "alacs"
version = "0.1.0"
edition = "2021"
description = "ALACS file format and tools"
license = "MIT"
authors = ["Comments Are Important <comments.are.important@gmail.com>"]

[dependencies]
