[package]
name = "tindalwic"
version = "0.1.0"
edition = "2024"
description = "tindalwic data format and tools"
license = "MIT"
authors = ["Comments Are Important <comments.are.important@gmail.com>"]

[dependencies]
indexmap = "2"
memchr = { version = "2.7.6", default-features = false }

[dev-dependencies]
markdown = "1.0.0"
